### PR TITLE
Check if click event came from keyboard  #82

### PR DESCRIPTION
**Pull request by jaylandro**
This is a proposed fix for a click event being emitted by keyboard navigation on a link.

Issue described below
https://github.com/Zulko/eagle.js/issues/82#issue-446209408

### CODE REVIEW

**Comment by Zulko** [comment]
Thanks for this! This looks good to me and pretty harmless. @yaodingyd any objections?

**Comment by yaodingyd** [comment]
LGTM

**Comment by Zulko** [comment]
@jaylandro it seems that your commit broke the Travis build because of a small cosmetic problem. Can you please fix the syntax until the build passes?

**Comment by yaodingyd** [comment]
@jaylandro Can you fix the linting error?

**Comment by jaylandro** [comment]
@Zulko Fixed. Thanks!

**Comment by Nanzaa1** [comment]
vertical help

**Comment by Nanzaa1** [comment]
@Zulko  vertical help

**Pull request merged**
