### PR TITLE
#6 added throttling for Mac touchpad

### PR DESCRIPTION
**Pull request by vittorio**
You need to play with throttling time. 1000 – it's good for Mac but i'm not sure about other devices.
If you don't want to have lodash as dependency you can just clone one throttle method from that.
It's just quick fix for #6 :)

### CODE REVIEW

**Comment by Zulko** [comment]
shouldn't it be debounce instead of throttle ? From what i understand, throttle will still perform all events, just space them, while debounce will discard the events after the first.

**Comment by vittorio** [comment]
@Zulko, sorry for silence. Will try to play with it in next few days

**Comment by QuentinRoy** [comment]
I agree that debounce might be more appropriate, however debounce usually trigger a function **after** it has not been called for x amount of time. In this case it might be a bit annoying as it would slow down the interaction. We might want to be sure it is called on the "leading edge of the timeout", (option `leading` with [lodash's `debounce`](https://lodash.com/docs/#debounce).

**Comment by yaodingyd** [comment]
Fixed with bd14f5b and 0d771b3

**Pull request closed without merging**
